### PR TITLE
I think I'm done. :))

### PR DESCRIPTION
**Pull request by charles26lee**
Maybe the only things we could add are a menu screen and a scrolling background, but those aren't really necessary so we're basically done. :>

### CODE REVIEW

**Comment by JerelynCo** [comment]
I'll be going back to Katipunan tomorrow (I can't do anything here at home ERGH). I'll try to add stuff to your code. Huhu. Don't do anything anymore Charles! :( :(

**Comment by charles26lee** [comment]
Hahahaha. Okay. I won't. Moving on to Theo now. :))

On 2 January 2015 at 20:11, Jerelyn Co <notifications@github.com> wrote:

> I'll be going back to Katipunan tomorrow (I can't do anything here at home
> ERGH). I'll try to add stuff to your code. Huhu. Don't do anything anymore
> Charles! :( :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JerelynCo/HW04/pull/4#issuecomment-68522790>.
>



-- 

*Charles Edward C. Lee*
*BS Computer Engineering*

**Comment by JerelynCo** [comment]
It's funny that you haven't changed the window name yet. It's still SDL Tutorial. hahaha!

**Comment by charles26lee** [comment]
Oh shit. I just noticed that. Hahahahaha. Yeah, I'll leave that to you.
:))))

**Comment by JerelynCo** [comment]
Aye! :)

**Pull request merged**
